### ISSUE TITLE
I continue to get next build error : "could not resolve project : ESP32CSISerial" 

### ISSUE THREAD

**Issue by Loki-moon** [StevenMHernandez/Android-CSI-Labelling-App#4]
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :ESP32CSISerial.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ESP32CSISerial:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

This error occurred when I tried to get a git and build it into an Android studio. 

I don't know what I did wrong.... T_T
(I just turned on the git without changing the code)

----------------------------

Oops..!! i'm sorry, 
I checked and found that the ESP32CSISERIAL folder was empty,
so I received the library from the git "https://github.com/StevenMHernandez/Android-ESP32-CSI" 
and it worked well... I was a fool.

**Comment by StevenMHernandez** [comment]
I am glad you were able to resolve this issue. By resolving this issue yourself, you have proved that you are not a fool :) 

In fact, sharing this issue and documenting the resolution will help future users of this project. So thank you!
